### ISSUE TITLE
Register busted?

### ISSUE THREAD

**Issue by benkaiser** [davidwilemski/openrunlog#79]
Went to the website to try it out but it looks like registering is busted. I can give more information about what information I put in if needed?

**Comment by davidwilemski** [comment]
Hey Ben, I found the issue and it was a small operational issue so I went ahead and it should be resolved now. Thanks for reporting.

I should note that any maintenance/bugfixes in the code base and on the site has been paused as I've joined @strava to build a similar service but for more sports and with a larger community. I will try to note that on this repo for others.
